mobs:register_mob("mobsplus:lava_flan", {
	type = "monster",
	hp_max = 10,
	collisionbox = {-0.5, -0.5, -0.5, 0.5, 1.5, 0.5},
	visual = "mesh",
	mesh = "zmobs_lava_flan.x",
	textures = {"zmobs_lava_flan.png"},
	visual_size = {x=1, y=1},
	makes_footstep_sound = true,
	view_range = 10,
	walk_velocity = 0.5,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:lava_source",
		chance = 15,
		min = 1,
		max = 1,},
		{name = "mobsplus:egg_lava_flan",
		chance = 2,
		min = 1,
		max = 1,},
	},
	light_resistant = true,
	armor = 80,
	drawtype = "front",
	water_damage = 5,
	lava_damage = 0,
	light_damage = 0,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 8,
		walk_start = 10,
		walk_end = 18,
		run_start = 20,
		run_end = 28,
		punch_start = 20,
		punch_end = 28,
	}
})
mobs:register_spawn("mobsplus:lava_flan", {"default:lava_source"}, 15, -1, 1000, 10, 0, "hostile")
mobs:register_egg("mobsplus","lava_flan","Lava flan")